### ISSUE TITLE
Multi-threading dimension issue

### ISSUE THREAD

**Issue by Geph** [whimc/Position-Tracker#6]
```
[10:17:43] [Server thread/INFO]: There are 0 of a max of 96 players online:
[10:18:52] [Server thread/INFO]: There are 0 of a max of 96 players online:
[10:20:02] [Server thread/INFO]: There are 0 of a max of 96 players online:
[10:21:12] [Server thread/INFO]: There are 0 of a max of 96 players online:
[10:22:21] [Server thread/INFO]: There are 0 of a max of 96 players online:
[10:22:52] [User Authenticator whimc/Path-Displayer#1/INFO]: UUID of player golithsnowman is 0398e052-3ca7-4836-9cbf-7916d8cae0af
[10:22:53] [Server thread/INFO]: golithsnowman joined the game
[10:22:53] [Server thread/INFO]: golithsnowman[/172.222.137.132:59244] logged in with entity id 2742 at ([Build]-200.96927078783744, 73.0, -137.3238105290535)
[10:22:53] [Server thread/WARN]: [WHIMC-PositionTracker] Task #8682 for WHIMC-PositionTracker v2.0.3 generated an exception
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_16_R3.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24) ~[patched_1.16.5.jar:git-Paper-445]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.biomeBaseToBiome(CraftBlock.java:516) ~[patched_1.16.5.jar:git-Paper-445]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.getBiome(CraftWorld.java:1087) ~[patched_1.16.5.jar:git-Paper-445]
	at org.bukkit.craftbukkit.v1_16_R3.block.CraftBlock.getBiome(CraftBlock.java:503) ~[patched_1.16.5.jar:git-Paper-445]
	at edu.whimc.positiontracker.sql.Queryer$PositionEntry.<init>(Queryer.java:33) ~[?:?]
	at edu.whimc.positiontracker.sql.Queryer.lambda$storePositionData$2(Queryer.java:75) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281]
	at java.util.Iterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281]
	at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281]
	at edu.whimc.positiontracker.sql.Queryer.storePositionData(Queryer.java:76) ~[?:?]
	at edu.whimc.positiontracker.Tracker.lambda$startRunner$1(Tracker.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-445]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-445]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293) ~[patched_1.16.5.jar:git-Paper-445]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-445]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-445]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-445]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-445]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[10:22:55] [Server thread/WARN]: [WHIMC-PositionTracker] Task #8682 for WHIMC-PositionTracker v2.0.3 generated an exception
java.lang.NullPointerException: null
```

**Comment by jackah2** [comment]
This is actually due to the world being generated by a custom resource pack. Since the biome is custom, the namespace key doesn't exist for it. The same console error can be seen in other plugins when interacting with these custom biomes. A fix would be to surround the troubled line of code in a `try`/`catch` and replace the biome with "unknown" if such an error occurs.
